### ISSUE TITLE
Fix: Slider Box sometimes hidden behind toolbar 

### ISSUE THREAD

**Issue by Mark2Mark** [Mark2Mark/variable-font-preview#10]
<img width="958" alt="Screenshot 2021-08-20 at 13 19 16" src="https://user-images.githubusercontent.com/5824595/130225779-f9732b34-db7e-4f34-9611-6563a7a5997c.png">

Only when preview is in standalone window, not when it is docked.

From a user:
macOS 11.2.3
macOS 11.5.2 
GlyphsApp 3.0.4 3097

Cannot reproduce with 
macOS 11.4
GlyphsApp 3.0.4 3097

🤔

**Comment by Mark2Mark** [comment]
User reported it to not occur with macOS 12.1 anymore.
Closed until someone else reports it.

Currently I can reproduce when the Glyphs window is verry narrow and the toolbar grows in height (12.1, but probably same with macOS 11)

**Comment by gorjious** [comment]
Just saw this is in the closed section after posting https://github.com/Mark2Mark/variable-font-preview/issues/23#issue-1718606981
