### ISSUE TITLE
Preview panel blocks bottom of Info box

### ISSUE THREAD

**Issue by LibertyType** [Mark2Mark/variable-font-preview#14]
G3.0.5 [311x] macOS 10.13.6
When opening or changing tabs, the Preview panel covers the bottom (Groups line) of the Info box until the user clicks on the Preview panel, then the view changes so it is all visible. An annoyance more than anything but it would save time if it were fixed.

<img width="612" alt="Screen shots" src="https://user-images.githubusercontent.com/2348503/160039407-1348b250-40c7-46ad-95c8-b07a8cb3d0a3.png">

**Comment by Mark2Mark** [comment]
Hi @LibertyType , thanks!
I am not quite sure I understand. The preview in the bottom is not from Variable Font Preview, but from GlyphsApp.

How exactly is this related? Does this only happen when VFP is active?

**Comment by LibertyType** [comment]
My apologies!!!! I posted this in the wrong place. It is related to Kernkraft! I obviously wasn't thinking. If you can move it, please do so; if not, just delete it.

As to the gray, that is how it appears until I click on the Preview panel.

**Comment by Mark2Mark** [comment]
Thanks!

Can you post that into the Kernkraft repo please?
And maybe a bit more specific about the build number? the 311x is slightly too loose :)
