### ISSUE TITLE
Ability to change font size and adjust window

### ISSUE THREAD

**Issue by gorjious** [Mark2Mark/variable-font-preview#18]
I find it difficult to use VFP on a 13in laptop. As the top preview panel is linked to the bottom preview panel, there is too much loss in screen real-estate. The separate preview panel helps somewhat in that regard but it still adds too much above the displayed glyphs, and resizing the window causes the font size to be reduced as well. 

Even with using an external monitor, it becomes difficult to find a balance between the various windows (all the more difficult as VFP is always displayed on top of the main app).

I think perhaps the simplest solution is to allow users to the change the displayed font size either by pinch-zoom, slider (on preview window or hidden in double click option menu), as well as, the ability to resizing the preview window without affecting the font size (or some other way that reduces the amount of addtional whitespace).

**Comment by Mark2Mark** [comment]
Thanks a lot. 

- [ ] Disconnecting the preview height from the bottom preview is in the works
- [ ] Adjusting the font size additionally will be considered.

**Comment by gorjious** [comment]
Hi Mark. Getting back into testing using VFP and not being able to not control the font size of what is in the preview is still a major hindrance to using the plugin.

There is even a weird bug where when I change to another window/app, the separate preview window becomes hidden (that part is fine) but when I return back to Glyphs, the VPR window shows a somewhat large(r) size and then immediately becomes small again. This also occurs when Always on Top is enabled.

Using my second monitor where the screen is 13in tall, the font size only gets to be 2.5in.

I hope the ability to manually adjust font size is still under consideration.

**Comment by Mark2Mark** [comment]
Hi @gorjious 

Thanks for the feedback. This sounds a little like a bug that was reported by one other user, and we could not yet find the problem (as I cannot reproduce it at all). I hope to find the culprit at soon. Also the font size is on the list. However, I am currently, unfortunately, not able to work on this. Probably until the end of this year. Sorry about that.

**Comment by gorjious** [comment]
Good to there the bug isn't an isolated case. If I can find a way to replicate it, I'll let you know. 
Appreciate the reply and looking forward to the future update.

**Comment by 75th** [comment]
I don't know about @gorjious, but my problem with the preview window font size is that the window wastes a ton of vertical space that the native Glyphs preview pane doesn't:

![Screenshot 2023-03-30 at 8 09 55 PM](https://user-images.githubusercontent.com/1731790/228997711-94206053-7bd2-4b1d-b3bc-84d53c530909.png)

If VFP had reasonable top padding like the Glyphs one does, scaling the font automatically with the preview pane would suit me just fine.

**Comment by Mark2Mark** [comment]
Hey @75th, thank you!
Does your font has a different UPM than 1000? I suspect that is the reason for your example.

**Comment by 75th** [comment]
@Mark2Mark Nope, it's 1000. According to mekkablue scripts, the highest glyph on any master is `ringcomb.case` on the highest weight. Its tallest point is at 1096, which looks like this:

![Screenshot 2023-03-31 at 6 51 46 AM](https://user-images.githubusercontent.com/1731790/229113727-bd8f47c5-3e88-47e1-8352-3e09496ef64d.png)

*However,* I've just noticed something very weird.

**Comment by 75th** [comment]
In taking more screenshots for you, I've figured out the problem. I'm on a MacBook Pro with a Retina display, but Glyphs is on an external non-Retina display. If I put Glyphs on the Retina display, the preview is sized correctly; on a non-Retina display, it's half as tall as the preview pane.

**Comment by 75th** [comment]
![Screenshot 2023-03-31 at 8 26 03 AM](https://user-images.githubusercontent.com/1731790/229135210-c4ac6fd6-1031-4ae5-a1db-7d6ff967c423.png)

- MacBookPro18,4 (14″ M1 Max)
- macOS Ventura 13.2.1
- Glyphs 3.1.2 (3151) but this has happened as long as I've had Glyphs

**Comment by Mark2Mark** [comment]
Thank you! I’ll have a look

**Comment by 75th** [comment]
No improvement for me on version 3.4.3. Exact same behavior as described above.

**Comment by Mark2Mark** [comment]
Thanks! Please [see my comment here](https://github.com/Mark2Mark/variable-font-preview/issues/22#issuecomment-1555737420)

A new version could fix it, but I need your help to check, as I still cannot reproduce and am making these changes "blindly".

**Comment by Mark2Mark** [comment]
closed with 85252a2, font size issue moved here: #21
