### ISSUE TITLE
Changing `opsz` axis first, distorts lettershapes

### ISSUE THREAD

**Issue by clauseggers** [Mark2Mark/variable-font-preview#20]
**Describe the bug**
This is an issue in the cosmetic department, but nevertheless an issue. I have a typeface with three axes, and as they are presented in VFP the optical size axis is the first one. When I activate VFP, and as the first thing I do change the value of the `opsz` axis, then VFP renders distorted outlines.

Video attached.

Latest MacOS, cutting edge Glyphs (the issue has always existed as I remember it)

https://user-images.githubusercontent.com/868987/222674313-e9bfb398-6b7e-4451-a7a2-41b6c1154c20.mov

**Comment by Mark2Mark** [comment]
Hi @clauseggers,

Thanks a lot! Can you send me a dummy file where this happens? For instance a file with only one glyph, but all the axes and masters.

**Comment by clauseggers** [comment]
You can have the whole file (it’s OSS)
[Playfair-2_1-Roman.glyphs.zip](https://github.com/Mark2Mark/variable-font-preview/files/10880712/Playfair-2_1-Roman.glyphs.zip)

**Comment by Mark2Mark** [comment]
On a side note: (shameless self promotion) as I see so many guide lines in your screenshot: Do you know about Mark Zones? Have you tried it? I am about to publish a documentation and tutorials soon, but maybe [this gives you a little](https://github.com/Mark2Mark/mark-zones-plugin) hint already.

**Comment by Mark2Mark** [comment]
Thanks a lot for the file. Will have a look!

**Comment by clauseggers** [comment]
The mark zones are not quite what I want. I need groups of guides that I can turn on/off depending on which glyphs I am working on. I recently made a mock-up for Georg. He wasn’t interested.
![guides](https://user-images.githubusercontent.com/868987/222690824-c0f5c7b7-5d0f-42cc-b2f7-9c81993c9fe9.png)

**Comment by Mark2Mark** [comment]
I think that is exactly what mark zones does. The zones are basically pairs of guides, and they only show in glyphs that fulfil certain conditions, like Script, Case, Small Cap, Numbers, etc.
You can customise these in your Master’s custom parameters, assign colors, and they also help you to see if a node is in or on the border. They show the name for the zone (pair) and you can also have overshoot per zone or a zone that is just one line. How is that not what you need?

**Comment by clauseggers** [comment]
Your solution is too cumbersome to work with. As I showed in my mockup I want a sidebar panel where I can group, colour, lock, and make (in)visible. I want to be able to select guides, cut them, and paste them in a guides group.

**Comment by Mark2Mark** [comment]
Okay, thanks for explaining. I don’t find it cumbersome at all, the setup is as simple as selecting two nodes and click "Make Zone". Copy+Paste, color, show/hide is all possible. A sidebar panel can easily be added. But fair enough, if it doesn’t work for you, no problem :)

**Comment by Mark2Mark** [comment]
cross-reference: https://github.com/Mark2Mark/mark-zones-plugin/issues/4

**Comment by Mark2Mark** [comment]
@clauseggers does the main problem of this issue still occur to you? I recently pushed an update (v3.6.0) which will now load the sliders with the axis default (or first master).

Your description sounds like what was caused before where the sliders all started with 0 (which caused the preview to look oddly extrapolated when the actual master min values where not 0)

**Comment by clauseggers** [comment]
It still happens, but I haven’t used the plugin in the last week or so.

**Comment by clauseggers** [comment]
It means that I have no clue which version is installed at any given time. I do not keep track of the versions of the auto-updated plugins. I used your plugin some time in the past, and at that time it did still exhibit the issue.

**Comment by Mark2Mark** [comment]
Thanks for explaining. Will close the issue now. If the still occurs and you have version 3.6 or later, feel free to reopen.
