### ISSUE TITLE
Ability to change font size and adjust window

### ISSUE THREAD

**Issue by Mark2Mark** [Mark2Mark/variable-font-preview#21]
_Originally reported by @gorjious in #18 but that issue was highjacked with another issue, so I reopen it here again._

---

"I find it difficult to use VFP on a 13in laptop. As the top preview panel is linked to the bottom preview panel, there is too much loss in screen real-estate. The separate preview panel helps somewhat in that regard but it still adds too much above the displayed glyphs, and resizing the window causes the font size to be reduced as well.

Even with using an external monitor, it becomes difficult to find a balance between the various windows (all the more difficult as VFP is always displayed on top of the main app).

I think perhaps the simplest solution is to allow users to the change the displayed font size either by pinch-zoom, slider (on preview window or hidden in double click option menu), as well as, the ability to resizing the preview window without affecting the font size (or some other way that reduces the amount of addtional whitespace)."

**Comment by 75th** [comment]
I suspect that @gorjious's "it still adds too much above the displayed glyphs" is a reference to the issue this was split from; I don't think I hijacked it. Agreed that we should still be able to change the font size independently, but I think the original reporter will be a happier camper already.

**Comment by Mark2Mark** [comment]
Don’t get me wrong, please don’t be offended. I just want to have my repository clean and changing the font size is a different thing. Hence I just separated the issues so that I can work well with it. The other issue started to be about different things, and it is hard to handle that if it is all in one issue.

Even this one issue shows several problems that need to be adressed. For example


> As the top preview panel is linked to the bottom preview panel,

This is odd to me, as the top preview panel is not linked at all to the bottom panel since almost 2 years. So I suspect that @gorjious might not have gotten any updates since a while. Which is very curious, if that is really the case.

**Comment by Mark2Mark** [comment]
But maybe I misunderstood the OP’s description and it might be solved as you say with the closing of the other issue #18 

I will close it now. Feel free to re-open. :)

**Comment by gorjious** [comment]
Just got a new computer so adding back plugins. Will test on the new and old setups and report back.

**Comment by Mark2Mark** [comment]
If you need help transferring your licenses, please let me know via email :)

Thanks everyone for all your help!
