### ISSUE TITLE
Slider and menu license key is not displayed.

### ISSUE THREAD

**Issue by greenreport** [Mark2Mark/variable-font-preview#28]
Slider is not displayed.
Pop-up menu for entering the license key does not open
Menu Paddler for the license key cannot be opened
Reinstalling Glyphs 3 or the plugin did not help

## Versions
 - macOS: 12.6.7
 - GlyphsApp Version build number 3151
 - Version 3.6
![Bildschirmfoto 2024-03-13 um 00 20 04](https://github.com/Mark2Mark/variable-font-preview/assets/119879285/8f8ca11d-7391-4c6d-b998-b72b6f854bf3)
![Bildschirmfoto 2024-03-13 um 00 27 19](https://github.com/Mark2Mark/variable-font-preview/assets/119879285/b6985195-a7fa-48ff-87da-eb74c9aa1b79)

**Comment by Mark2Mark** [comment]
Thanks,

There are 2 issues in one:
1. Missing sliders
2. Missing/faulty Paddle purchase item

---

1.
You can solve this issue by using a newer version of Glyphs. Note that you can have multiple versions of glyphs in parallel. So keep your current version around (as a backup) and load a newer cutting edge that you can use until I have fixed that bug with older Glyphs versions. 

Find all [Glyphs versions here](florianpircher.com/glyphs/versions/).



---

2.
The Paddle issue should be solved as well with a newer Glyphs version, but please let me know if it still persists.

---

Sorry for the trouble, hope it helps. Good luck and let me know :)

**Comment by greenreport** [comment]
Hi, maybe this helps? From the Terminal:

2024-03-13 17:40:51.650 Glyphs 3[7427:175464] Plugin loading: Problem with plugin at path (Info): (null)
2024-03-13 17:40:56.149 Glyphs 3[7427:175464] principalClass time: 4.494743  ShowStyles.glyphsReporter
2024-03-13 17:40:56.230 Glyphs 3[7427:175464] 'Variable Font Preview 3' Paddle Bundle: 4.4.0 (4.4.0)
2024-03-13 17:40:56.254 Glyphs 3[7427:175464] Number of MIDI sources: 0
2024-03-13 17:40:56.258 Glyphs 3[7427:175464] Could not listen on port com.GeorgSeifert.Glyphs3
2024-03-13 17:40:56.258 Glyphs 3[7427:175464] Could not listen on port com.GeorgSeifert.Glyphs3.3151

**Comment by greenreport** [comment]
Unfortunately, the latest version (3.1.2) makes no difference. The problem only arose a few days ago.

**Comment by Mark2Mark** [comment]
No, you need one of the newer versions. It needs to be a 3.1

Please find them here:

https://florianpircher.com/glyphs/versions/

**Comment by greenreport** [comment]
> No, you need one of the newer versions. It needs to be a 3.2
> 
> Please find them here:
> 
> https://florianpircher.com/glyphs/versions/

It works. Thanks a lot!

**Comment by Mark2Mark** [comment]
Awesome. Thanks for letting me know!
Sorry for the inconvenience.
