### ISSUE TITLE
[solved] Sliders are not visible

### ISSUE THREAD

**Issue by gorjious** [Mark2Mark/variable-font-preview#29]
## Describe the bug
The sliders are not visible and it seems like the the whole controls section has collapsed. There is a tiny portion that I can two-finger click to see the menu options. This occurs with the preview window is both attached and detached.

I've tried deleting it from the Plugin Manager then restart -> reinstall -> restart.

## Screenshots
<img width="1150" alt="Screenshot 2024-04-18 at 2 00 37 PM" src="https://github.com/Mark2Mark/variable-font-preview/assets/23149420/20b08b29-5f70-4c77-8822-ea94b8c1e720">

<img width="1255" alt="Screenshot 2024-04-18 at 1 59 34 PM" src="https://github.com/Mark2Mark/variable-font-preview/assets/23149420/f3bba428-a48a-466d-a567-b64bc39f8fb2">

## Versions
 - macOS: [Ventura 13.3.1]
 - GlyphsApp Version build number [3.1.2 (3151)
 - Version [3.6]

**Comment by Mark2Mark** [comment]
Hi @gorjious 

Please update Glyphs. The latest version is 3.2 and updating Glyphs will fix this issue right away.
