### ISSUE TITLE
Bug: With Glyphs 3.2 the dashed outlines are glitchy

### ISSUE THREAD

**Issue by Mark2Mark** [Mark2Mark/variable-font-preview#31]
@schriftgestalt: This is new with Glyphs 3.2 and I did not touch the drawing code in the plugin. Do you know what might suddenly cause that?

In the clip you see how initially the outlines are dashed as supposed to. Then when panning the view, they suddenly lose the dash and get solid. That is the bug.

Zooming triggers them to get their dash back.

This happens in all kind of scenarios now, the video shows just one case.

https://github.com/Mark2Mark/variable-font-preview/assets/5824595/6181a618-3d82-4010-9d60-f6012f600e91

**Comment by schriftgestalt** [comment]
I would need to see the drawing code.

**Comment by Mark2Mark** [comment]
You have access to the private repo. main-G3 branch is the one live.

**Comment by Mark2Mark** [comment]
Another note:
I see it only happen in some glyphs of my test font.
/a /o /s for example, but not in /b /c /f /g /h /n /e, etc

I cannot find out what is different in those glyphs. Anchors or background seems not to cause interferences, as those are present or not in those mentioned glyphs crosswise.
(the /s and /S now work fine though)
Causing glyphs don’t have any special layers either.

**Comment by schriftgestalt** [comment]
In the `setLineDash` call, you use a `dashArray[4]` and a count of 4. But only the first fields are set. Use a count of 2 and it should work.

**Comment by Mark2Mark** [comment]
This has likely been it. Thank you so so much! 🙏

(fixed in 3.7.6)
