### ISSUE TITLE
Animate (play) the variable axis

### ISSUE THREAD

**Issue by sovichet** [Mark2Mark/variable-font-preview#32]
A similar concept from Font Gauntlet is the ability for the app to animate the variable axis (or multiple axes if the graphic drawing performance is not an issue). This allows us to see what's happening with our drawings quickly. It's okay to drag the slider manually, but having an animating feature could be quite helpful.

**Comment by Mark2Mark** [comment]
This is a feature that has been requested several times and is currently in the works :)

**Comment by Mark2Mark** [comment]
implemented and live now with version 3.7
