### ISSUE TITLE
More space above and below in the Preview window

### ISSUE THREAD

**Issue by sovichet** [Mark2Mark/variable-font-preview#33]
I could not see the glyphs that stay deeper or higher in the floating Preview window.

![telegram-cloud-photo-size-5-6219768954721779440-y](https://github.com/Mark2Mark/variable-font-preview/assets/1669566/413b66e2-13d1-4544-872f-d5a69ba7df87)

(This is from the chat we had on Telegram.)

**Comment by Mark2Mark** [comment]
Thanks, @sovichet 

This is fixed now with the version v3.7.5 (will be live in the next days)

You can then use the Custom Parameters "Preview Ascender/Descender" or "winAscend/winDescend" to scale the preview in the same way is Glyphs does it in the built in previews.

**Comment by sovichet** [comment]
@Mark2Mark It's working nicely. ❤️

**Comment by Mark2Mark** [comment]
Thanks for letting me know. Spread the word 🤩
