### ISSUE TITLE
No icons for Cyrillic

### ISSUE THREAD

**Issue by eweracs** [Mark2Mark/variable-font-preview#35]
## Describe the bug
When measuring stems of Cyrillic glyphs, stems do not have an icon indicator like they do in the Latin.

## To Reproduce
1. Open a Cyrillic glyph (e.g. ge-cy)
2. Measure its horizontal stem
3. See there is no icon like in the Latin

## Expected behavior
I would expect to see icons like in the Latin.

## Screenshots
<img width="764" alt="image" src="https://github.com/user-attachments/assets/8b93ac99-96e6-4733-84b0-f176efb36c61">

**Comment by Mark2Mark** [comment]
Thanks Sebastian. Did you mean to put that issue into Show Stems (instead of Variable Font Preview)?

**Comment by eweracs** [comment]
Oops, my bad. Yes, sorry.

https://github.com/Mark2Mark/show-stems-pro-plugin/issues/14
