### ISSUE TITLE
Fix virtual masters and bracket/brace layers

### ISSUE THREAD

**Issue by Mark2Mark** [Mark2Mark/variable-font-preview#5]

**Comment by HansG1** [comment]
Have you any idea, when we could expect a solution for this? 
Thanks and many cheers

Hans

**Comment by Mark2Mark** [comment]
Hi Hans, do you have a little sample font where you have issues with? It does not need to be complete, just a glyph and all important data removed, if you want. 

It's easier to trouble shoot when I have example troublesome files to test with. 

Thanks in advance.

**Comment by Mark2Mark** [comment]
virtual masters should work now again since v3.6.0
